-- Yochiyochi (English) schema
-- Run this once in a fresh Supabase project's SQL Editor (or via `supabase db push`).
-- Matches the shape described in types/database.ts and README.md.

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.gardens (
  id           uuid primary key default gen_random_uuid(),
  member_code  text not null unique,
  name         text,
  created_at   timestamptz not null default now()
);

create table if not exists public.garden_members (
  id          uuid primary key default gen_random_uuid(),
  garden_id   uuid not null references public.gardens(id) on delete cascade,
  user_id     uuid not null references auth.users(id) on delete cascade,
  role        text not null default 'staff',
  created_at  timestamptz not null default now(),
  unique (garden_id, user_id)
);

create table if not exists public.foods (
  id          bigint generated by default as identity primary key,
  garden_id   uuid references public.gardens(id) on delete cascade,
  name        text not null,
  created_at  timestamptz not null default now()
);

create table if not exists public.food_aliases (
  id       bigint generated by default as identity primary key,
  food_id  bigint not null references public.foods(id) on delete cascade,
  alias    text not null
);

create table if not exists public.cooking_methods (
  id          bigint generated by default as identity primary key,
  food_id     bigint not null references public.foods(id) on delete cascade,
  garden_id   uuid references public.gardens(id) on delete cascade,
  phase1      text,
  phase2      text,
  phase3      text,
  phase4      text,
  phase5      text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (food_id, garden_id)
);

create table if not exists public.children (
  id          uuid primary key default gen_random_uuid(),
  garden_id   uuid not null references public.gardens(id) on delete cascade,
  name        text not null,
  age_month   integer,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.child_food_restrictions (
  id          uuid primary key default gen_random_uuid(),
  child_id    uuid not null references public.children(id) on delete cascade,
  food_id     bigint not null references public.foods(id) on delete cascade,
  cannot_eat  boolean not null default true,
  note        text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.accidents (
  id          uuid primary key default gen_random_uuid(),
  garden_id   uuid references public.gardens(id) on delete set null,
  child_id    uuid references public.children(id) on delete set null,
  food_id     bigint not null references public.foods(id),
  content     text not null,
  is_public   boolean not null default false,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
create index if not exists idx_garden_members_user_id on public.garden_members(user_id);
create index if not exists idx_garden_members_garden_id on public.garden_members(garden_id);
create index if not exists idx_foods_garden_id on public.foods(garden_id);
create index if not exists idx_foods_name on public.foods(name);
create index if not exists idx_food_aliases_food_id on public.food_aliases(food_id);
create index if not exists idx_food_aliases_alias on public.food_aliases(alias);
create index if not exists idx_cooking_methods_food_id on public.cooking_methods(food_id);
create index if not exists idx_cooking_methods_garden_id on public.cooking_methods(garden_id);
create index if not exists idx_children_garden_id on public.children(garden_id);
create index if not exists idx_child_food_restrictions_child_id on public.child_food_restrictions(child_id);
create index if not exists idx_child_food_restrictions_food_id on public.child_food_restrictions(food_id);
create index if not exists idx_accidents_garden_id on public.accidents(garden_id);
create index if not exists idx_accidents_child_id on public.accidents(child_id);
create index if not exists idx_accidents_food_id on public.accidents(food_id);
create index if not exists idx_accidents_is_public on public.accidents(is_public);

-- ---------------------------------------------------------------------------
-- updated_at trigger helper
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_cooking_methods_updated_at on public.cooking_methods;
create trigger trg_cooking_methods_updated_at
  before update on public.cooking_methods
  for each row execute function public.set_updated_at();

drop trigger if exists trg_children_updated_at on public.children;
create trigger trg_children_updated_at
  before update on public.children
  for each row execute function public.set_updated_at();

drop trigger if exists trg_child_food_restrictions_updated_at on public.child_food_restrictions;
create trigger trg_child_food_restrictions_updated_at
  before update on public.child_food_restrictions
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.gardens enable row level security;
alter table public.garden_members enable row level security;
alter table public.foods enable row level security;
alter table public.food_aliases enable row level security;
alter table public.cooking_methods enable row level security;
alter table public.children enable row level security;
alter table public.child_food_restrictions enable row level security;
alter table public.accidents enable row level security;

-- Helper: the garden_id(s) the current auth.uid() belongs to.
-- (Expressed inline as a subquery in each policy below, since Postgres RLS
-- policies can't call a SECURITY DEFINER function that itself queries a
-- RLS-protected table without care; the inline subquery form is simplest
-- and keeps garden_members' own policy authoritative.)

-- ---- gardens -----------------------------------------------------------
-- Only the service role (which bypasses RLS) reads/writes this table today
-- (registration, login lookup, account deletion all go through supabaseAdmin).
-- No anon/authenticated policies are defined, so normal clients get zero rows.

-- ---- garden_members ------------------------------------------------------
create policy "members can read their own membership"
  on public.garden_members for select
  to authenticated
  using (user_id = auth.uid());

-- ---- foods -----------------------------------------------------------
create policy "anyone can read shared foods"
  on public.foods for select
  to anon, authenticated
  using (garden_id is null);

create policy "members can read their garden's foods"
  on public.foods for select
  to authenticated
  using (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );

create policy "members can insert foods for their garden"
  on public.foods for insert
  to authenticated
  with check (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );

create policy "members can update their garden's foods"
  on public.foods for update
  to authenticated
  using (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  )
  with check (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );

create policy "members can delete their garden's foods"
  on public.foods for delete
  to authenticated
  using (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );

-- ---- food_aliases ------------------------------------------------------
-- Read-only for everyone; only the service role writes (see delete-account route).
create policy "anyone can read food aliases"
  on public.food_aliases for select
  to anon, authenticated
  using (true);

-- ---- cooking_methods -----------------------------------------------------
create policy "anyone can read shared cooking methods"
  on public.cooking_methods for select
  to anon, authenticated
  using (garden_id is null);

create policy "members can read their garden's cooking methods"
  on public.cooking_methods for select
  to authenticated
  using (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );

create policy "members can insert cooking methods for their garden"
  on public.cooking_methods for insert
  to authenticated
  with check (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );

create policy "members can update their garden's cooking methods"
  on public.cooking_methods for update
  to authenticated
  using (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  )
  with check (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );

create policy "members can delete their garden's cooking methods"
  on public.cooking_methods for delete
  to authenticated
  using (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );

-- ---- children ------------------------------------------------------------
create policy "members can read their garden's children"
  on public.children for select
  to authenticated
  using (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );

create policy "members can insert children for their garden"
  on public.children for insert
  to authenticated
  with check (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );

create policy "members can update their garden's children"
  on public.children for update
  to authenticated
  using (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  )
  with check (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );

create policy "members can delete their garden's children"
  on public.children for delete
  to authenticated
  using (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );

-- ---- child_food_restrictions ----------------------------------------------
create policy "members can read their garden's food restrictions"
  on public.child_food_restrictions for select
  to authenticated
  using (
    child_id in (
      select c.id from public.children c
      where c.garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
    )
  );

create policy "members can insert food restrictions for their garden"
  on public.child_food_restrictions for insert
  to authenticated
  with check (
    child_id in (
      select c.id from public.children c
      where c.garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
    )
  );

create policy "members can update their garden's food restrictions"
  on public.child_food_restrictions for update
  to authenticated
  using (
    child_id in (
      select c.id from public.children c
      where c.garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
    )
  )
  with check (
    child_id in (
      select c.id from public.children c
      where c.garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
    )
  );

create policy "members can delete their garden's food restrictions"
  on public.child_food_restrictions for delete
  to authenticated
  using (
    child_id in (
      select c.id from public.children c
      where c.garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
    )
  );

-- ---- accidents -----------------------------------------------------------
create policy "anyone can read public incidents"
  on public.accidents for select
  to anon, authenticated
  using (is_public = true);

create policy "members can read their garden's incidents"
  on public.accidents for select
  to authenticated
  using (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );

create policy "members can insert incidents for their garden"
  on public.accidents for insert
  to authenticated
  with check (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );

create policy "members can update their garden's incidents"
  on public.accidents for update
  to authenticated
  using (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  )
  with check (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );

create policy "members can delete their garden's incidents"
  on public.accidents for delete
  to authenticated
  using (
    garden_id in (select gm.garden_id from public.garden_members gm where gm.user_id = auth.uid())
  );
